#----------------------------------------------------------------------
# DiffuScent Configuration File
#
# This file contains all parameters needed to run the gas diffusion simulation
# for the DiffuScent project. Parameters are organized into sections.
#----------------------------------------------------------------------

# Room dimensions and mesh resolution
room:
  # Physical dimensions of the room in meters
  width: 5.0    # Width (x-direction)
  length: 4.0   # Length (y-direction)
  height: 2.5   # Height (z-direction)
  
  # Mesh resolution (number of cells in each direction)
  # Higher resolution = more accurate but slower simulation
  mesh_cells:
    nx: 50    # Number of cells in x-direction
    ny: 40    # Number of cells in y-direction
    nz: 25    # Number of cells in z-direction

# Gas properties and source characteristics
gas:
  # Gas type (for reference - currently just affects the name in outputs)
  name: "Taco Bell Banger"
  
  # Diffusion coefficient in air (m²/s)
  # This determines how quickly the gas spreads
  # Reference values for common gases at 20°C:
  # - Methane: 1.76e-5 m²/s
  # - Hydrogen sulfide: 1.76e-5 m²/s
  # - Carbon dioxide: 1.42e-5 m²/s
  diffusion_coefficient: 1.75e-5
  
  # Initial gas emission
  initial_volume_ml: 200.0  # Volume of gas released in milliliters
  
  # Initial concentration in ppm (parts per million)
  # 50,000 ppm = 5% concentration by volume
  initial_concentration_ppm: 50000.0
  
  # Source location as relative coordinates (0-1 in each dimension)
  # (0,0,0) is the bottom-left-front corner of the room
  # (1,1,1) is the top-right-back corner
  source_location: [0.1, 0.1, 0.1]  # Near floor in one corner
  
  # Source radius in meters
  # Approx. size of the initial gas cloud
  source_radius: 0.1

# Simulation time settings
simulation:
  # Total time to simulate in seconds
  total_time: 60.0
  
  # Time step for numerical solution in seconds
  # Smaller time steps = more accurate but slower simulation
  time_step: 0.5
  
  # Concentration threshold for detection in ppm
  # When concentration reaches this value at a detection point,
  # the gas is considered detected
  # Typical human detection threshold for H₂S (rotten egg smell): 0.5 ppm
  detection_threshold: 0.5

# Visualization settings
visualization:
  # Number of contour levels for plotting
  contour_levels: 10
  
  # Whether to save plots to files
  save_plots: true
  
  # Time interval between plots in seconds
  plot_interval: 5.0
