# DiffuScent Configuration
# Performance-optimized settings

simulation:
  # Reduced mesh resolution
  mesh:
    x_cells: 25  # Reduced from 50
    y_cells: 20  # Reduced from 40
    z_cells: 12  # Reduced from 25
    x_size: 5.0  # Room width in meters
    y_size: 4.0  # Room length in meters
    z_size: 2.5  # Room height in meters
  
  # Increased time step
  time:
    dt: 1.0      # Increased to 1 second (verified against stability criteria)
    total_time: 300.0  # 5 minutes of simulation
    save_interval: 10  # Save every 10 seconds
  
  # Performance settings
  performance:
    parallel_processing: true  # Enable optional parallel processing
    parallel_threads: 4        # Number of threads to use if supported
    visualization_during_computation: false  # Only generate plots at the end
    
# Physics model settings
physics:
  model: "advection_diffusion"  # Changed from "diffusion" to include advection
  
  # Gas properties
  gas_properties:
    # Molecular weights (g/mol)
    molecular_weights:
      methane: 16.04
      hydrogen_sulfide: 34.08
      nitrogen: 28.01
      oxygen: 32.0
      carbon_dioxide: 44.01
      hydrogen: 2.02
      ammonia: 17.03
      sulfur_dioxide: 64.07
  
  # Diffusion coefficients
  diffusion:
    methane: 0.000022  # m²/s
    hydrogen_sulfide: 0.000018  # m²/s
    nitrogen: 0.000020  # m²/s
    oxygen: 0.000021  # m²/s
    carbon_dioxide: 0.000016  # m²/s
    hydrogen: 0.000061  # m²/s
    ammonia: 0.000023  # m²/s
    sulfur_dioxide: 0.000013  # m²/s
    
  # Added initial momentum
  initial_velocity:
    speed: 3.0  # m/s
    angle_horizontal: 0.0  # degrees (0 = straight forward)
    angle_vertical: 30.0  # degrees downward
    
  # Buoyancy settings
  buoyancy:
    enabled: true
    room_temperature: 20.0  # Celsius
    gas_temperature: 37.0   # Celsius
    
  # Room air circulation
  air_circulation:
    enabled: true
    pattern: "basic"  # basic, hvac, or custom
    strength: 0.2     # m/s average air speed

# Gas release properties (standard profile)
gas:
  profile: "standard"
  volume: 0.5  # liters
  composition:
    methane: 0.60
    hydrogen_sulfide: 0.00001
    carbon_dioxide: 0.20
    nitrogen: 0.15
    oxygen: 0.05
    
# Detection settings
detection:
  thresholds:
    hydrogen_sulfide: 0.00047  # ppm - odor detection threshold
    ammonia: 5.0  # ppm
    sulfur_dioxide: 0.1  # ppm
    methane: 5000.0  # ppm - not detectable by smell
    carbon_dioxide: 10000.0  # ppm - not detectable by smell
  positions:
    - name: "colleague"
      x: 2.5
      y: 3.0
      z: 1.5
    - name: "boss"
      x: 4.0
      y: 3.5
      z: 1.5

# Visualization settings
visualization:
  concentration_scale: "logarithmic"  # linear or logarithmic
  detection_markers: true
  color_map: "plasma"  # matplotlib colormap
  slice_views:
    - plane: "xy"
      z: 1.5
    - plane: "xz"
      y: 2.0
    - plane: "yz"
      x: 2.5
